name: Teste Pick Up Runner

on:
  workflow_dispatch:

jobs:
  pick:
    runs-on: ferdletasks
    steps:
    - name: pick job
      run: echo "Job picked up"
  setup:  
    runs-on: ferdletasks
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  install:
    runs-on: ferdletasks
    steps:
    - name: Install Python
      run: |
       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
       brew install python3
      
