name: Teste Pick Up Runner

on:
  workflow_dispatch:

jobs:
  setup:
  
    runs-on: ferdletasks

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
  pick:
    runs-on: ferdletasks
    steps:
    - name: Checkout
    - name: pick job
      run: echo "Job picked up"
